==203210== Helgrind, a thread error detector
==203210== Copyright (C) 2007-2017, and GNU GPL'd, by OpenWorks LLP et al.
==203210== Using Valgrind-3.18.1 and LibVEX; rerun with -h for copyright info
==203210== Command: ./bin/kernel ESTABILIDAD_GENERAL 0 estabilidad_general.config
==203210== 
==203210== ---Thread-Announcement------------------------------------------
==203210== 
==203210== Thread #3 was created
==203210==    at 0x49A19F3: clone (clone.S:76)
==203210==    by 0x49A28EE: __clone_internal (clone-internal.c:83)
==203210==    by 0x49106D8: create_thread (pthread_create.c:295)
==203210==    by 0x49111FF: pthread_create@@GLIBC_2.34 (pthread_create.c:828)
==203210==    by 0x4853767: ??? (in /usr/libexec/valgrind/vgpreload_helgrind-amd64-linux.so)
==203210==    by 0x10E625: inicializar_servidores (kernel.c:121)
==203210==    by 0x10DF71: main (kernel.c:7)
==203210== 
==203210== ---Thread-Announcement------------------------------------------
==203210== 
==203210== Thread #1 is the program's root thread
==203210== 
==203210== ----------------------------------------------------------------
==203210== 
==203210== Possible data race during write of size 1 at 0x4AA8B10 by thread #3
==203210== Locks held: none
==203210==    at 0x48597B4: mempcpy (in /usr/libexec/valgrind/vgpreload_helgrind-amd64-linux.so)
==203210==    by 0x4907664: _IO_new_file_xsputn (fileops.c:1235)
==203210==    by 0x4907664: _IO_file_xsputn@@GLIBC_2.2.5 (fileops.c:1196)
==203210==    by 0x48F300B: outstring_func (vfprintf-internal.c:239)
==203210==    by 0x48F300B: __vfprintf_internal (vfprintf-internal.c:1517)
==203210==    by 0x48DC79E: printf (printf.c:33)
==203210==    by 0x4874A34: txt_write_in_stdout (txt.c:32)
==203210==    by 0x48757EF: _log_write_in_level (log.c:166)
==203210==    by 0x487537E: log_debug (log.c:95)
==203210==    by 0x11059A: esperar_cliente (socket.c:56)
==203210==    by 0x10E6EA: iniciar_cpu_dispatch (kernel.c:137)
==203210==    by 0x485396A: ??? (in /usr/libexec/valgrind/vgpreload_helgrind-amd64-linux.so)
==203210==    by 0x4910AC2: start_thread (pthread_create.c:442)
==203210==    by 0x49A1A03: clone (clone.S:100)
==203210== 
==203210== This conflicts with a previous write of size 1 by thread #1
==203210== Locks held: none
==203210==    at 0x4859796: mempcpy (in /usr/libexec/valgrind/vgpreload_helgrind-amd64-linux.so)
==203210==    by 0x4907664: _IO_new_file_xsputn (fileops.c:1235)
==203210==    by 0x4907664: _IO_file_xsputn@@GLIBC_2.2.5 (fileops.c:1196)
==203210==    by 0x48FCF1B: puts (ioputs.c:40)
==203210==    by 0x10DF80: main (kernel.c:9)
==203210==  Address 0x4aa8b10 is 0 bytes inside a block of size 1,024 alloc'd
==203210==    at 0x484A919: malloc (in /usr/libexec/valgrind/vgpreload_helgrind-amd64-linux.so)
==203210==    by 0x48FABA3: _IO_file_doallocate (filedoalloc.c:101)
==203210==    by 0x4909CDF: _IO_doallocbuf (genops.c:347)
==203210==    by 0x4908F5F: _IO_file_overflow@@GLIBC_2.2.5 (fileops.c:744)
==203210==    by 0x49076D4: _IO_new_file_xsputn (fileops.c:1243)
==203210==    by 0x49076D4: _IO_file_xsputn@@GLIBC_2.2.5 (fileops.c:1196)
==203210==    by 0x48F300B: outstring_func (vfprintf-internal.c:239)
==203210==    by 0x48F300B: __vfprintf_internal (vfprintf-internal.c:1517)
==203210==    by 0x48DC79E: printf (printf.c:33)
==203210==    by 0x4874A34: txt_write_in_stdout (txt.c:32)
==203210==    by 0x48757EF: _log_write_in_level (log.c:166)
==203210==    by 0x487537E: log_debug (log.c:95)
==203210==    by 0x10E2EE: inicializar_kernel (kernel.c:62)
==203210==    by 0x10DF67: main (kernel.c:6)
==203210==  Block was alloc'd by thread #1
==203210== 
==203210== ---Thread-Announcement------------------------------------------
==203210== 
==203210== Thread #4 was created
==203210==    at 0x49A19F3: clone (clone.S:76)
==203210==    by 0x49A28EE: __clone_internal (clone-internal.c:83)
==203210==    by 0x49106D8: create_thread (pthread_create.c:295)
==203210==    by 0x49111FF: pthread_create@@GLIBC_2.34 (pthread_create.c:828)
==203210==    by 0x4853767: ??? (in /usr/libexec/valgrind/vgpreload_helgrind-amd64-linux.so)
==203210==    by 0x10E642: inicializar_servidores (kernel.c:122)
==203210==    by 0x10DF71: main (kernel.c:7)
==203210== 
==203210== ----------------------------------------------------------------
==203210== 
==203210== Possible data race during write of size 1 at 0x4AAA9B0 by thread #4
==203210== Locks held: none
==203210==    at 0x48597B4: mempcpy (in /usr/libexec/valgrind/vgpreload_helgrind-amd64-linux.so)
==203210==    by 0x4907664: _IO_new_file_xsputn (fileops.c:1235)
==203210==    by 0x4907664: _IO_file_xsputn@@GLIBC_2.2.5 (fileops.c:1196)
==203210==    by 0x48FBA9C: fputs (iofputs.c:38)
==203210==    by 0x48749FA: txt_write_in_file (txt.c:27)
==203210==    by 0x48757A1: _log_write_in_level (log.c:158)
==203210==    by 0x487537E: log_debug (log.c:95)
==203210==    by 0x11059A: esperar_cliente (socket.c:56)
==203210==    by 0x10F9EC: iniciar_cpu_interrupt (kernel.c:520)
==203210==    by 0x485396A: ??? (in /usr/libexec/valgrind/vgpreload_helgrind-amd64-linux.so)
==203210==    by 0x4910AC2: start_thread (pthread_create.c:442)
==203210==    by 0x49A1A03: clone (clone.S:100)
==203210== 
==203210== This conflicts with a previous write of size 1 by thread #3
==203210== Locks held: none
==203210==    at 0x4859796: mempcpy (in /usr/libexec/valgrind/vgpreload_helgrind-amd64-linux.so)
==203210==    by 0x4907664: _IO_new_file_xsputn (fileops.c:1235)
==203210==    by 0x4907664: _IO_file_xsputn@@GLIBC_2.2.5 (fileops.c:1196)
==203210==    by 0x48FBA9C: fputs (iofputs.c:38)
==203210==    by 0x48749FA: txt_write_in_file (txt.c:27)
==203210==    by 0x48757A1: _log_write_in_level (log.c:158)
==203210==    by 0x487537E: log_debug (log.c:95)
==203210==    by 0x11059A: esperar_cliente (socket.c:56)
==203210==    by 0x10E6EA: iniciar_cpu_dispatch (kernel.c:137)
==203210==  Address 0x4aaa9b0 is 0 bytes inside a block of size 4,096 alloc'd
==203210==    at 0x484A919: malloc (in /usr/libexec/valgrind/vgpreload_helgrind-amd64-linux.so)
==203210==    by 0x48FABA3: _IO_file_doallocate (filedoalloc.c:101)
==203210==    by 0x4909CDF: _IO_doallocbuf (genops.c:347)
==203210==    by 0x4908F5F: _IO_file_overflow@@GLIBC_2.2.5 (fileops.c:744)
==203210==    by 0x49076D4: _IO_new_file_xsputn (fileops.c:1243)
==203210==    by 0x49076D4: _IO_file_xsputn@@GLIBC_2.2.5 (fileops.c:1196)
==203210==    by 0x48FBA9C: fputs (iofputs.c:38)
==203210==    by 0x48749FA: txt_write_in_file (txt.c:27)
==203210==    by 0x48757A1: _log_write_in_level (log.c:158)
==203210==    by 0x487537E: log_debug (log.c:95)
==203210==    by 0x10E2EE: inicializar_kernel (kernel.c:62)
==203210==    by 0x10DF67: main (kernel.c:6)
==203210==  Block was alloc'd by thread #1
==203210== 
==203210== ---Thread-Announcement------------------------------------------
==203210== 
==203210== Thread #5 was created
==203210==    at 0x49A19F3: clone (clone.S:76)
==203210==    by 0x49A28EE: __clone_internal (clone-internal.c:83)
==203210==    by 0x49106D8: create_thread (pthread_create.c:295)
==203210==    by 0x49111FF: pthread_create@@GLIBC_2.34 (pthread_create.c:828)
==203210==    by 0x4853767: ??? (in /usr/libexec/valgrind/vgpreload_helgrind-amd64-linux.so)
==203210==    by 0x10E738: iniciar_cpu_dispatch (kernel.c:143)
==203210==    by 0x485396A: ??? (in /usr/libexec/valgrind/vgpreload_helgrind-amd64-linux.so)
==203210==    by 0x4910AC2: start_thread (pthread_create.c:442)
==203210==    by 0x49A1A03: clone (clone.S:100)
==203210== 
==203210== ----------------------------------------------------------------
==203210== 
==203210== Possible data race during write of size 1 at 0x4AAA9EA by thread #5
==203210== Locks held: none
==203210==    at 0x4859796: mempcpy (in /usr/libexec/valgrind/vgpreload_helgrind-amd64-linux.so)
==203210==    by 0x4907664: _IO_new_file_xsputn (fileops.c:1235)
==203210==    by 0x4907664: _IO_file_xsputn@@GLIBC_2.2.5 (fileops.c:1196)
==203210==    by 0x48FBA9C: fputs (iofputs.c:38)
==203210==    by 0x48749FA: txt_write_in_file (txt.c:27)
==203210==    by 0x48757A1: _log_write_in_level (log.c:158)
==203210==    by 0x487537E: log_debug (log.c:95)
==203210==    by 0x11101C: saludar_cliente_generico (socket.c:312)
==203210==    by 0x10E7A5: atender_dispatch (kernel.c:152)
==203210==    by 0x485396A: ??? (in /usr/libexec/valgrind/vgpreload_helgrind-amd64-linux.so)
==203210==    by 0x4910AC2: start_thread (pthread_create.c:442)
==203210==    by 0x49A1A03: clone (clone.S:100)
==203210== 
==203210== This conflicts with a previous write of size 1 by thread #4
==203210== Locks held: none
==203210==    at 0x48597B4: mempcpy (in /usr/libexec/valgrind/vgpreload_helgrind-amd64-linux.so)
==203210==    by 0x4907664: _IO_new_file_xsputn (fileops.c:1235)
==203210==    by 0x4907664: _IO_file_xsputn@@GLIBC_2.2.5 (fileops.c:1196)
==203210==    by 0x48FBA9C: fputs (iofputs.c:38)
==203210==    by 0x48749FA: txt_write_in_file (txt.c:27)
==203210==    by 0x48757A1: _log_write_in_level (log.c:158)
==203210==    by 0x487537E: log_debug (log.c:95)
==203210==    by 0x11059A: esperar_cliente (socket.c:56)
==203210==    by 0x10F9EC: iniciar_cpu_interrupt (kernel.c:520)
==203210==  Address 0x4aaa9ea is 58 bytes inside a block of size 4,096 alloc'd
==203210==    at 0x484A919: malloc (in /usr/libexec/valgrind/vgpreload_helgrind-amd64-linux.so)
==203210==    by 0x48FABA3: _IO_file_doallocate (filedoalloc.c:101)
==203210==    by 0x4909CDF: _IO_doallocbuf (genops.c:347)
==203210==    by 0x4908F5F: _IO_file_overflow@@GLIBC_2.2.5 (fileops.c:744)
==203210==    by 0x49076D4: _IO_new_file_xsputn (fileops.c:1243)
==203210==    by 0x49076D4: _IO_file_xsputn@@GLIBC_2.2.5 (fileops.c:1196)
==203210==    by 0x48FBA9C: fputs (iofputs.c:38)
==203210==    by 0x48749FA: txt_write_in_file (txt.c:27)
==203210==    by 0x48757A1: _log_write_in_level (log.c:158)
==203210==    by 0x487537E: log_debug (log.c:95)
==203210==    by 0x10E2EE: inicializar_kernel (kernel.c:62)
==203210==    by 0x10DF67: main (kernel.c:6)
==203210==  Block was alloc'd by thread #1
==203210== 
